### ISSUE TITLE
SSL problem with avatar

### ISSUE THREAD

**Issue by conconnl** [JoomShaper/mod_sp_tweet#3]
The SP Tweet isn't 100% compatible with HTTPS websites.
The module displays the image with a HTTP based URI (http://pbs.twimg.com)
This is a issue for HTTPS websites with HSTS enabled.

Can you please fix this, I already tried to change the code a replaced all HTTP schemes to HTTPS but this not fix the avatar problem.

**Comment by ruchikanagarkar** [comment]
did you try using the github codebase for the module? I faced a similar issue when I downloaded the module from the website but then I used the github code and it worked fine for https.

**Comment by conconnl** [comment]
Thanks
The GitHub base sort of works. 
It's not 100% compatible with the default of Joomla. It doesn't follow the global settings in Joomla like other modules and components. 

I think they need to fix something and update the website.

**Comment by ruchikanagarkar** [comment]
Welcome :) and yes they need to update in their website .
